import { ServiceItem, TestimonialItem, FAQItem } from './types';

export const CLINIC_INFO = {
  name: 'Dr NGUETSOP Jessica',
  title: 'Specialist in general and laparoscopic surgery',
  titleFr: 'Spécialiste en chirurgie générale et cœlioscopique',
  phone: '+213 698 96 63 28',
  email: 'dr.nguetsop.jessica@gmail.com',
  address: 'Main Crossroads, El Oued, Algeria',
  addressFr: 'Carrefour Principal, El Oued, Algérie',
  social: {
    facebook: 'https://facebook.com',
    whatsapp: 'https://wa.me/213698966328',
    instagram: 'https://instagram.com',
  },
};

export const SERVICES_DATA: ServiceItem[] = [
  {
    id: 'gastrointestinal',
    title: 'Gastrointestinal Surgery',
    titleFr: 'Chirurgie Gastro-Intestinale',
    category: 'digestive',
    duration: '60–120 min',
    stay: '1–3 jours',
    description: 'Specialized interventions on the stomach, colon, and intestines using micro-invasive laparoscopic technology for gentle recovery.',
    descriptionFr: 'Interventions de pointe sur l’estomac, le côlon et l’intestin par cœlioscopie micro-invasive pour un rétablissement rapide et serein.',
    iconType: 'stomach',
    details: {
      overview: 'Specialized interventions on the stomach, intestines, colon, and rectum utilizing state-of-the-art minimally invasive and open approaches.',
      overviewFr: 'Prise en charge chirurgicale experte des pathologies de l’estomac, de l’intestin grêle, du côlon et du rectum par voie cœlioscopique mini-invasive.',
      indications: ['Gastric ulcers & complications', 'Bowel obstructions & resections', 'Colorectal pathology & benign tumors', 'Gastroesophageal reflux surgery'],
      indicationsFr: ['Ulcères gastriques et complications', 'Occlusions & résections intestinales', 'Pathologies colorectales et tumeurs bénignes', 'Chirurgie du reflux gastro-œsophagien (RGO)'],
      technique: 'Advanced minimally invasive laparoscopy ensuring minimal scarring, reduced postoperative pain, and rapid gastrointestinal transit recovery.',
      techniqueFr: 'Laparoscopie mini-invasive avancée avec micro-incisions, garantissant de très faibles cicatrices, une douleur minime et une reprise rapide du transit.',
      recovery: 'Average hospital stay 2–4 days; return to light routine within 10–14 days.',
      recoveryFr: 'Séjour clinique moyen de 1 à 3 jours ; reprise progressive des activités quotidiennes en 10 à 14 jours.',
    },
  },
  {
    id: 'emergencies',
    title: 'Surgical Emergencies',
    titleFr: 'Urgences Chirurgicales',
    category: 'emergency',
    duration: 'Immédiat 24/7',
    stay: 'Surveillance dédiée',
    description: 'Immediate 24/7 emergency response for acute abdominal pain, appendicitis, peritonitis, and visceral trauma with dedicated triage.',
    descriptionFr: 'Prise en charge d’urgence 24h/24 des syndromes abdominaux aigus, appendicites, péritonites et occlusions avec bloc opératoire dédié.',
    isFeatured: true,
    iconType: 'emergency',
    details: {
      overview: 'Round-the-clock acute surgical intervention for sudden abdominal conditions, peritonitis, acute appendicitis, and visceral trauma.',
      overviewFr: 'Interventions chirurgicales d’urgence 24h/24 pour affections aiguës : appendicite, occlusion, perforation d’ulcère et péritonite.',
      indications: ['Acute appendicitis', 'Perforated peptic ulcer & peritonitis', 'Strangulated or incarcerated hernia', 'Intestinal occlusion & acute ischemia'],
      indicationsFr: ['Appendicite aiguë compliquée ou simple', 'Péritonite et perforation d’ulcère', 'Hernie étranglée ou engouée', 'Occlusion intestinale aiguë'],
      technique: 'Immediate triage and exploratory laparoscopic/laparotomic surgery with advanced hemodynamic and antibiotic surveillance.',
      techniqueFr: 'Triage immédiat, exploration cœlioscopique d’urgence sous surveillance anesthésique continue et antibiothérapie ciblée.',
      recovery: 'Monitored inpatient recovery tailored strictly to the acute pathology and patient response.',
      recoveryFr: 'Surveillance clinique attentive adaptée à la pathologie initiale et au confort immédiat du patient.',
    },
  },
  {
    id: 'laser-hemorrhoid',
    title: 'Laser Hemorrhoid Surgery',
    titleFr: 'Chirurgie Laser des Hémorroïdes',
    category: 'laser',
    duration: '20–35 min',
    stay: 'Ambulatoire (même jour)',
    description: 'Cutting-edge diode laser proctology (LHP) without cuts or open wounds, ensuring painless same-day outpatient discharge.',
    descriptionFr: 'Traitement au laser diode de dernière génération (LHP) sans incision ni plaie ouverte, permettant un retour à domicile le jour même.',
    iconType: 'laser',
    details: {
      overview: 'Next-generation diode laser treatment for internal and external hemorrhoidal disease (LHP - Laser Hemorrhoidoplasty).',
      overviewFr: 'Traitement moderne par thermo-ablation laser diode des hémorroïdes sans suture ni excision cutanée douloureuse.',
      indications: ['Grade II, III, and IV hemorrhoidal disease', 'Persistent rectal bleeding & prolapse', 'Chronic anal fissures resistant to topical care'],
      indicationsFr: ['Maladie hémorroïdaire stades II, III et IV', 'Saignements récurrents et prolapsus', 'Fissures anales chroniques rebelles'],
      technique: 'Targeted laser fiber ablation shrinks hemorrhoidal nodes from the inside without cutting, incisions, or painful open wounds.',
      techniqueFr: 'Fibre optique laser introduite au cœur du paquet hémorroïdaire pour coagulation interne ciblée sans cicatrice ouverte.',
      recovery: 'Same-day outpatient discharge; painless or mild discomfort; resume routine activity in 48–72 hours.',
      recoveryFr: 'Sortie ambulatoire en quelques heures ; douleurs légères à quasi-nulles ; reprise du travail en 48 à 72 heures.',
    },
  },
  {
    id: 'cholecystectomy',
    title: 'Cholecystectomy Surgery',
    titleFr: 'Chirurgie de la Vésicule Biliaire',
    category: 'digestive',
    duration: '40–60 min',
    stay: '24h ou ambulatoire',
    description: 'Minimally invasive laparoscopic removal of the gallbladder for gallstones, recurrent colic, and acute cholecystitis.',
    descriptionFr: 'Ablation cœlioscopique de la vésicule pour calculs biliaires, coliques hépatiques et cholécystites avec micro-orifices.',
    iconType: 'cholecystectomy',
    details: {
      overview: 'Laparoscopic gallbladder removal for gallstones, symptomatic biliary colic, cholecystitis, and gallbladder polyps.',
      overviewFr: 'Cholécystectomie par cœlioscopie pour lithiase biliaire symptomatique, crises douloureuses ou cholécystite aiguë.',
      indications: ['Symptomatic cholelithiasis (gallstones)', 'Acute and chronic cholecystitis', 'Gallbladder dyskinesia & polyps'],
      indicationsFr: ['Lithiase vésiculaire symptomatique (calculs)', 'Cholécystite aiguë et subaiguë', 'Polypes vésiculaires et dyskinésies'],
      technique: '4 micro-incisions under high-definition video camera guidance; clip-ligation of cystic duct and artery with safe extraction.',
      techniqueFr: 'Quatre micro-incisions sous guidage vidéo Full HD ; ligature sécurisée du canal cystique et de l’artère cystique puis extraction sous sac stérile.',
      recovery: '24-hour stay or ambulatory discharge; low discomfort; return to regular diet and desk work within 5 to 7 days.',
      recoveryFr: 'Hospitalisation de 24 heures ou sortie ambulatoire ; alimentation reprise le soir même ; reprise du travail en 5 à 7 jours.',
    },
  },
  {
    id: 'thyroid',
    title: 'Thyroid Surgery',
    titleFr: 'Chirurgie de la Thyroïde',
    category: 'general',
    duration: '60–90 min',
    stay: '24–48h',
    description: 'Gentle partial or total thyroidectomy with nerve-monitoring and aesthetic low-cervical micro-incisions with invisible stitching.',
    descriptionFr: 'Thyroïdectomie partielle ou totale préservant les cordes vocales et les parathyroïdes, avec cicatrice esthétique invisible.',
    iconType: 'thyroid',
    details: {
      overview: 'Comprehensive partial or total thyroidectomy for benign thyroid nodules, multinodular goiters, hyperthyroidism, and suspicious lesions.',
      overviewFr: 'Intervention experte sur la glande thyroïde (lobectomie ou thyroïdectomie totale) pour nodules, goitres volumineux ou hyperthyroïdie.',
      indications: ['Compressive goiter causing swallowing or breathing strain', 'Hyperactive toxic nodules / Graves disease', 'Suspicious cytological nodule biopsy'],
      indicationsFr: ['Goitre volumineux gênant la déglutition ou la voix', 'Nodules toxiques / hyperthyroïdie', 'Nodules suspects à la ponction cytologique'],
      technique: 'Careful preservation of recurrent laryngeal nerves and parathyroid glands via aesthetic low-cervical collar incision with intradermal stitching.',
      techniqueFr: 'Repérage et préservation méticuleuse des nerfs récurrents et glandes parathyroïdes avec surjet intradermique résorbable.',
      recovery: '1–2 days clinical observation with vocal cord monitoring and safe calcium balance checks.',
      recoveryFr: 'Surveillance de 24 à 48 heures avec contrôle de la phonation et du calcium sérique.',
    },
  },
  {
    id: 'hernia',
    title: 'Hernia Surgery',
    titleFr: 'Chirurgie des Hernies & Éventrations',
    category: 'general',
    duration: '30–50 min',
    stay: 'Ambulatoire / 24h',
    description: 'Tension-free laparoscopic mesh reinforcement for inguinal, umbilical, and incisional abdominal wall defects.',
    descriptionFr: 'Cure de hernie inguinale, ombilicale ou d’éventration par pose de renfort prothétique sans tension par laparoscopie.',
    iconType: 'hernia',
    details: {
      overview: 'Tension-free repair of inguinal, femoral, umbilical, and incisional ventral hernias using biocompatible prosthetic mesh.',
      overviewFr: 'Réparation sans tension des parois abdominales (hernies inguinales, ombilicales, crurales) par filet prothétique de haute tolérance.',
      indications: ['Primary and recurrent inguinal hernias', 'Umbilical and epigastric wall defects', 'Post-operative incisional hernia (eventration)'],
      indicationsFr: ['Hernies inguinales uni ou bilatérales', 'Hernies ombilicales et de la ligne blanche', 'Éventrations post-opératoires'],
      technique: 'Laparoscopic TAPP/TEP pre-peritoneal mesh repair or customized Lichtenstein technique for permanent muscular reinforcement.',
      techniqueFr: 'Approche cœlioscopique TAPP ou TEP pré-péritonéale pour renfort solide, absence de tension et cicatrices minimes.',
      recovery: 'Outpatient or overnight stay; immediate ambulation; light exercise resumed in 2 weeks.',
      recoveryFr: 'Sortie le jour même ou après 24h ; reprise de la marche immédiate ; activités sportives après 2 à 3 semaines.',
    },
  },
];

export const TESTIMONIALS_DATA: TestimonialItem[] = [
  {
    id: '1',
    name: 'Amina Mansouri',
    city: 'El Oued',
    rating: 5.0,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    review: 'Dr. NGUETSOP Jessica and her team took exceptional care of me during my laparoscopic gallbladder surgery. No pain, quick recovery, and immense kindness.',
    reviewFr: 'Le Dr NGUETSOP Jessica et son équipe ont été remarquables pour ma chirurgie de la vésicule par cœlioscopie. Zéro douleur, reprise très rapide et une écoute humaine exceptionnelle.',
  },
  {
    id: '2',
    name: 'Karim Bouzid',
    city: 'Alger',
    rating: 5.0,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    review: 'I travelled from Algiers for laser hemorrhoid treatment with Dr. NGUETSOP. I returned home the very same afternoon without any unbearable pain. Truly miraculous.',
    reviewFr: 'J’ai fait le déplacement pour le traitement hémorroïdaire au laser avec le Dr NGUETSOP. Je suis rentré chez moi le jour même sans douleur invalidante. Un vrai savoir-faire chirurgical.',
  },
  {
    id: '3',
    name: 'Youcef Benali',
    city: 'El Oued',
    rating: 5.0,
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&auto=format&fit=crop&q=80',
    review: 'Admitted in emergency for acute appendicitis in the middle of the night. Dr. NGUETSOP handled the surgery masterfully with minimal scars. I am infinitely grateful.',
    reviewFr: 'Admis en urgence en pleine nuit pour une crise d’appendicite aiguë. Le Dr NGUETSOP a opéré avec une grande maîtrise en cœlioscopie. Cicatrices invisibles et rétablissement parfait.',
  },
  {
    id: '4',
    name: 'Samira Belkacem',
    city: 'Tamanrasset',
    rating: 4.8,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    review: 'Total thyroidectomy done with extraordinary delicacy. My voice was completely normal immediately upon waking up, and the incision mark is nearly invisible.',
    reviewFr: 'Thyroïdectomie réalisée avec une minutie extraordinaire. Ma voix était parfaitement normale dès le réveil et la cicatrice au cou est discrète et très belle.',
  },
  {
    id: '5',
    name: 'Rachid Mebarki',
    city: 'Touggourt',
    rating: 4.9,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    review: 'Inguinal hernia repaired using laparoscopic mesh. Walking was easy on day 2. A true professional surgeon who takes the time to explain everything thoroughly.',
    reviewFr: 'Hernie inguinale opérée sous cœlioscopie. J’ai pu remarcher facilement dès le lendemain. Une chirurgienne brillante et pédagogue qui rassure ses patients.',
  },
];

export const FAQ_DATA: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'What are the main advantages of laparoscopic (keyhole) surgery?',
    questionFr: 'Quels sont les avantages de la chirurgie par cœlioscopie (mini-invasive) ?',
    answer: 'Laparoscopic surgery uses miniature incisions (5 to 10 mm) and high-resolution cameras. This significantly minimizes surgical trauma, reduces postoperative pain, reduces infection risk, and allows patients to resume normal life within days instead of weeks.',
    answerFr: 'La cœlioscopie s’effectue via de minuscules incisions (5 à 10 mm) guidées par caméra HD. Cela réduit drastiquement le traumatisme des tissus, minimise les douleurs post-opératoires, limite les cicatrices et permet un retour à domicile et au travail beaucoup plus rapide.',
  },
  {
    id: 'faq-2',
    question: 'How do I prepare for my first surgical consultation with Dr. NGUETSOP?',
    questionFr: 'Comment préparer ma première consultation chirurgicale avec le Dr NGUETSOP ?',
    answer: 'Please bring your previous ultrasound or CT scans, latest blood test results, current medication list, and surgical history. For abdominal conditions, having a 4-hour fasting period prior to ultrasound exam is recommended.',
    answerFr: 'Munissez-vous de vos derniers bilans sanguins, comptes-rendus d’échographie ou de scanner, de votre ordonnance de traitements habituels et de vos antécédents médicaux. Pour une échographie abdominale complémentaire, un jeûne de 4 heures est conseillé.',
  },
  {
    id: 'faq-3',
    question: 'How does the laser hemorrhoid procedure (LHP) work?',
    questionFr: 'Comment se déroule l’intervention des hémorroïdes au laser (LHP) ?',
    answer: 'Under light sedation or locoregional anesthesia, a thin radial diode laser fiber is introduced inside the hemorrhoidal cushion. It coagulates the enlarged blood vessels from within without excising sensitive skin. It is virtually painless and performed in outpatient care.',
    answerFr: 'Sous anesthésie locale ou sédation légère, une fibre laser diode ultrafine est introduite au cœur du coussinet hémorroïdaire. La lumière laser résorbe le vaisseau de l’intérieur sans coupure ni plaie cutanée ouverte, éliminant les douleurs des chirurgies traditionnelles.',
  },
  {
    id: 'faq-4',
    question: 'How are surgical emergencies handled at the clinic?',
    questionFr: 'Comment sont gérées les urgences chirurgicales au cabinet ?',
    answer: 'Acute surgical emergencies (appendicitis, peritonitis, strangulated hernias, visceral occlusion) are prioritized immediately. You can reach our emergency line directly at +213 698 96 63 28.',
    answerFr: 'Les urgences chirurgicales aiguës (appendicite, péritonite, hernie étranglée, occlusion) font l’objet d’une prise en charge prioritaire immédiate. Vous pouvez contacter la ligne d’urgence directe au +213 698 96 63 28.',
  },
];
